apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gaddamidianil/food-delivery-frontend:latest
        ports:
        - containerPort: 5173
        env:
          - name: REACT_APP_BACKEND_URL
            value: http://backend-service:5001

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: food-delivery
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 5173
